#pragma once
#include <string>
#include <map>


constexpr auto FIX_Message_ReqLogon = "A";
constexpr auto FIX_Message_ReqLogout = "5";
constexpr auto FIX_Message_ReqHeartBeat = "0";
constexpr auto FIX_Message_ReqTestRequest = "1";
constexpr auto FIX_Message_ReqResendRequest = "2";
constexpr auto FIX_Message_ReqSequenceReset = "4";
constexpr auto FIX_Message_ReqNewOrder = "D";
constexpr auto FIX_Message_ReqOrderCancelRequest = "F";
constexpr auto FIX_Message_ReqOrderCancelReplaceRequest = "G";
constexpr auto FIX_Message_ReqOrderStatusRequest = "H";

constexpr auto FIX_Message_RspLogon = "A";
constexpr auto FIX_Message_RspLogout = "5";
constexpr auto FIX_Message_RspHeartBeat = "0";
constexpr auto FIX_Message_RspTestRequest = "1";
constexpr auto FIX_Message_RspResendRequest = "2";
constexpr auto FIX_Message_RspSessionLevelReject = "3";
constexpr auto FIX_Message_RspSequenceReset = "4";
constexpr auto FIX_Message_ExecutionReport = "8";
constexpr auto FIX_Message_RspOrderCancelReject = "9";


constexpr auto FIX_Account = 1;
constexpr auto FIX_AvgPx = 6;
constexpr auto FIX_BeginSeqNo = 7;
constexpr auto FIX_BeginString = 8;
constexpr auto FIX_BodyLength = 9;
constexpr auto FIX_CheckSum = 10;
constexpr auto FIX_ClOrdID = 11;
constexpr auto FIX_CumQty = 14;
constexpr auto FIX_Currency = 15;
constexpr auto FIX_EndSeqNo = 16;
constexpr auto FIX_ExecID = 17;
constexpr auto FIX_ExecRefID = 19;
constexpr auto FIX_ExecTransType = 20;
constexpr auto FIX_HandInst = 21;
constexpr auto FIX_SecurityIDSource = 22;
constexpr auto FIX_LastPx = 31;
constexpr auto FIX_LastQty = 32;
constexpr auto FIX_MsgType = 35;
constexpr auto FIX_MsgSeqNum = 34;
constexpr auto FIX_NewSeqNo = 36;
constexpr auto FIX_OrderID = 37;
constexpr auto FIX_OrderQty = 38;
constexpr auto FIX_OrderStatus = 39;
constexpr auto FIX_OrdType = 40;
constexpr auto FIX_OrigClOrdID = 41;
constexpr auto FIX_PossDupFlag = 43;
constexpr auto FIX_Price = 44;
constexpr auto FIX_RefSeqNum = 45;
constexpr auto FIX_SecurityID = 48;
constexpr auto FIX_SenderCompID = 49;
constexpr auto FIX_SenderSubID = 50;
constexpr auto FIX_SendingTime = 52;
constexpr auto FIX_Side = 54;
constexpr auto FIX_Symbol = 55;
constexpr auto FIX_TargetCompID = 56;
constexpr auto FIX_TargetSubID = 57;
constexpr auto FIX_Text = 58;
constexpr auto FIX_TimeInForce = 59;
constexpr auto FIX_TransactTime = 60;
constexpr auto FIX_SettlDate = 64;
constexpr auto FIX_TradeDate = 75;
constexpr auto FIX_NoAllocs = 78;
constexpr auto FIX_AllocAccount = 79;
constexpr auto FIX_StopPx = 99;
constexpr auto FIX_CxlRejReason = 102;
constexpr auto FIX_OrdRejReason = 103;
constexpr auto FIX_SecurityDesc = 107;
constexpr auto FIX_HeartBtInt = 108;
constexpr auto FIX_MinQty = 110;
constexpr auto FIX_TestReqID = 112;
constexpr auto FIX_QuoteID = 117;
constexpr auto FIX_OrigSendingTime = 122;
constexpr auto FIX_GapFillFlag = 123;
constexpr auto FIX_QuoteReqID = 131;
constexpr auto FIX_BidPx = 132;
constexpr auto FIX_OfferPx = 133;
constexpr auto FIX_BidSize = 134;
constexpr auto FIX_OfferSize = 135;
constexpr auto FIX_ResetSeqNumFlag = 141;
constexpr auto FIX_SenderLocationID = 142;
constexpr auto FIX_TargetLocationID = 143;
constexpr auto FIX_ExecType = 150;
constexpr auto FIX_LeavesQty = 151;
constexpr auto FIX_SecurityType = 167;
constexpr auto FIX_MaturityMonthYear = 200;
constexpr auto FIX_CustomerOrFirm = 204;
constexpr auto FIX_SecurityExchange = 207;
constexpr auto FIX_MaxShow = 210;
constexpr auto FIX_MarketDepth = 264;
constexpr auto FIX_QuoteEntryID = 299;
constexpr auto FIX_ContraTrader = 337;
constexpr auto FIX_EncodedTextLen = 354;
constexpr auto FIX_EncodedText = 355;
constexpr auto FIX_LastMsgSeqNumProcessed = 369;
constexpr auto FIX_RefTagID = 371;
constexpr auto FIX_RefMsgType = 372;
constexpr auto FIX_SessionRejectReason = 373;
constexpr auto FIX_ContraBroker = 375;
constexpr auto FIX_ExecRestatementReason = 378;
constexpr auto FIX_BusinessRejectReason = 380;
constexpr auto FIX_TotalNumSecurities = 393;
constexpr auto FIX_ExpireDate = 432;
constexpr auto FIX_CancelRejResponseTo = 434;
constexpr auto FIX_MultiLegReportingType = 442;
constexpr auto FIX_CFICode = 461;
constexpr auto FIX_UnderlyingProduct = 462;
constexpr auto FIX_SecondaryExecID = 527;
constexpr auto FIX_CrossID = 548;
constexpr auto FIX_CrossType = 549;
constexpr auto FIX_MinTradeVol = 562;
constexpr auto FIX_MassStatusReqID = 584;
constexpr auto FIX_SettlPriceType = 731;
constexpr auto FIX_LastUpdateTime = 779;
constexpr auto FIX_NextExpectedMsgSeqNum = 789;
constexpr auto FIX_UnderlyingPx = 810;
constexpr auto FIX_OptionDelta = 811;
constexpr auto FIX_AvgPXIndicator = 819;
constexpr auto FIX_NoEvents = 864;
constexpr auto FIX_EventType = 865;
constexpr auto FIX_NoInstAttrib = 870;
constexpr auto FIX_InstAttribType = 871;
constexpr auto FIX_InstAttribValue = 872;
constexpr auto FIX_LastRptRequest = 912;
constexpr auto FIX_HostCrossID = 961;
constexpr auto FIX_MinPriceIncrement = 969;
constexpr auto FIX_SecurityUpdateAction = 980;
constexpr auto FIX_UnitOfMeasure = 996;
constexpr auto FIX_MDFeedType = 1022;
constexpr auto FIX_ManualOrderIndicator = 1028;
constexpr auto FIX_CustOrderHandlingInst = 1031;
constexpr auto FIX_AggressorIndicator = 1057;
constexpr auto FIX_MaxTradeVol = 1140;
constexpr auto FIX_NoMdFeedTypes = 1141;
constexpr auto FIX_MatchAlgorithm = 1142;
constexpr auto FIX_MaxPriceVariation = 1143;
constexpr auto FIX_EventTime = 1145;
constexpr auto FIX_MinPriceIncrementAmount = 1146;
constexpr auto FIX_UnitOfMeasureQty = 1147;
constexpr auto FIX_LowLimitPrice = 1148;
constexpr auto FIX_HighLimitPrice = 1149;
constexpr auto FIX_TradingReferencePrice = 1150;
constexpr auto FIX_SecurityGroup = 1151;
constexpr auto FIX_ApplID = 1180;
constexpr auto FIX_Volatility = 1188;
constexpr auto FIX_ExpirationTimeValue = 1189;
constexpr auto FIX_RiskFreeRate = 1190;
constexpr auto FIX_NoLotTypeRules = 1234;
constexpr auto FIX_MarketSegmentID = 1300;
constexpr auto FIX_NoFills = 1362;
constexpr auto FIX_FillExecID = 1363;
constexpr auto FIX_FillPx = 1364;
constexpr auto FIX_FillQty = 1365;
constexpr auto FIX_EncryptedPasswordMethod = 1400;
constexpr auto FIX_EncryptedPasswordLen = 1401;
constexpr auto FIX_EncryptedPassword = 1402;
constexpr auto FIX_ClearingTradePriceType = 1598;
constexpr auto FIX_ApplicationSystemName = 1603;
constexpr auto FIX_ApplicationSystemVersion = 1604;
constexpr auto FIX_ApplicationSystemVendor = 1605;
constexpr auto FIX_FillYieldType = 1622;
constexpr auto FIX_AvgPxGroupID = 1731;
constexpr auto FIX_Memo = 5149;
constexpr auto FIX_ClearedVolume = 5791;
constexpr auto FIX_OpenInterestQty = 5792;
constexpr auto FIX_TradingReferenceDate = 5796;
constexpr auto FIX_MatchEventIndicator = 5799;
constexpr auto FIX_DecayStartDate = 5819;
constexpr auto FIX_DelayDuration = 5904;
constexpr auto FIX_RequestTime = 5979;
constexpr auto FIX_Asset = 6937;
constexpr auto FIX_SelfMatchPreventionID = 7928;
constexpr auto FIX_SelfMatchPreventionInstruction = 8000;
constexpr auto FIX_SplitMsg = 9553;
constexpr auto FIX_CtiCode = 9702;
constexpr auto FIX_OriginalSecondaryExecID = 9703;
constexpr auto FIX_GiveUpFirm = 9707;
constexpr auto FIX_CmtaGiveupCD = 9708;
constexpr auto FIX_CorrelationClOrdID = 9717;
constexpr auto FIX_OFMOverride = 9768;
constexpr auto FIX_NoProcessedEntries = 9772;
constexpr auto FIX_UserDefinedInstrument = 9779;
constexpr auto FIX_DisplayFactor = 9787;
constexpr auto FIX_MDTradeEntryID = 37711;


class FixItems
{
	FixItems();
	FixItems(const FixItems&) = delete;
	FixItems& operator=(const FixItems&) = delete;
public:
	static FixItems& GetInstance();
	int GetItemKey(std::string name);
	
private:
	static FixItems m_Instance;
	std::map<std::string, int> m_FixItems;
};
