#include "FixItems.h"

using namespace std;

FixItems FixItems::m_Instance;

FixItems::FixItems()
{
	m_FixItems["Account"] = 1;
	m_FixItems["AvgPx"] = 6;
	m_FixItems["BeginSeqNo"] = 7;
	m_FixItems["BeginString"] = 8;
	m_FixItems["BodyLength"] = 9;
	m_FixItems["CheckSum"] = 10;
	m_FixItems["ClOrdID"] = 11;
	m_FixItems["CumQty"] = 14;
	m_FixItems["Currency"] = 15;
	m_FixItems["EndSeqNo"] = 16;
	m_FixItems["ExecID"] = 17;
	m_FixItems["ExecRefID"] = 19;
	m_FixItems["ExecTransType"] = 20;
	m_FixItems["HandInst"] = 21;
	m_FixItems["SecurityIDSource"] = 22;
	m_FixItems["LastPx"] = 31;
	m_FixItems["LastQty"] = 32;
	m_FixItems["MsgType"] = 35;
	m_FixItems["MsgSeqNum"] = 34;
	m_FixItems["NewSeqNo"] = 36;
	m_FixItems["OrderID"] = 37;
	m_FixItems["OrderQty"] = 38;
	m_FixItems["OrderStatus"] = 39;
	m_FixItems["OrdType"] = 40;
	m_FixItems["OrigClOrdID"] = 41;
	m_FixItems["PossDupFlag"] = 43;
	m_FixItems["Price"] = 44;
	m_FixItems["RefSeqNum"] = 45;
	m_FixItems["SecurityID"] = 48;
	m_FixItems["SenderCompID"] = 49;
	m_FixItems["SenderSubID"] = 50;
	m_FixItems["SendingTime"] = 52;
	m_FixItems["Side"] = 54;
	m_FixItems["Symbol"] = 55;
	m_FixItems["TargetCompID"] = 56;
	m_FixItems["TargetSubID"] = 57;
	m_FixItems["Text"] = 58;
	m_FixItems["TimeInForce"] = 59;
	m_FixItems["TransactTime"] = 60;
	m_FixItems["SettlDate"] = 64;
	m_FixItems["TradeDate"] = 75;
	m_FixItems["NoAllocs"] = 78;
	m_FixItems["AllocAccount"] = 79;
	m_FixItems["StopPx"] = 99;
	m_FixItems["CxlRejReason"] = 102;
	m_FixItems["OrdRejReason"] = 103;
	m_FixItems["SecurityDesc"] = 107;
	m_FixItems["HeartBtInt"] = 108;
	m_FixItems["MinQty"] = 110;
	m_FixItems["TestReqID"] = 112;
	m_FixItems["QuoteID"] = 117;
	m_FixItems["OrigSendingTime"] = 122;
	m_FixItems["GapFillFlag"] = 123;
	m_FixItems["QuoteReqID"] = 131;
	m_FixItems["BidPx"] = 132;
	m_FixItems["OfferPx"] = 133;
	m_FixItems["BidSize"] = 134;
	m_FixItems["OfferSize"] = 135;
	m_FixItems["ResetSeqNumFlag"] = 141;
	m_FixItems["SenderLocationID"] = 142;
	m_FixItems["TargetLocationID"] = 143;
	m_FixItems["ExecType"] = 150;
	m_FixItems["LeavesQty"] = 151;
	m_FixItems["SecurityType"] = 167;
	m_FixItems["MaturityMonthYear"] = 200;
	m_FixItems["CustomerOrFirm"] = 204;
	m_FixItems["SecurityExchange"] = 207;
	m_FixItems["MaxShow"] = 210;
	m_FixItems["MarketDepth"] = 264;
	m_FixItems["QuoteEntryID"] = 299;
	m_FixItems["ContraTrader"] = 337;
	m_FixItems["EncodedTextLen"] = 354;
	m_FixItems["EncodedText"] = 355;
	m_FixItems["LastMsgSeqNumProcessed"] = 369;
	m_FixItems["RefTagID"] = 371;
	m_FixItems["RefMsgType"] = 372;
	m_FixItems["SessionRejectReason"] = 373;
	m_FixItems["ContraBroker"] = 375;
	m_FixItems["ExecRestatementReason"] = 378;
	m_FixItems["BusinessRejectReason"] = 380;
	m_FixItems["TotalNumSecurities"] = 393;
	m_FixItems["ExpireDate"] = 432;
	m_FixItems["CancelRejResponseTo"] = 434;
	m_FixItems["MultiLegReportingType"] = 442;
	m_FixItems["CFICode"] = 461;
	m_FixItems["UnderlyingProduct"] = 462;
	m_FixItems["SecondaryExecID"] = 527;
	m_FixItems["CrossID"] = 548;
	m_FixItems["CrossType"] = 549;
	m_FixItems["MinTradeVol"] = 562;
	m_FixItems["MassStatusReqID"] = 584;
	m_FixItems["SettlPriceType"] = 731;
	m_FixItems["LastUpdateTime"] = 779;
	m_FixItems["NextExpectedMsgSeqNum"] = 789;
	m_FixItems["UnderlyingPx"] = 810;
	m_FixItems["OptionDelta"] = 811;
	m_FixItems["AvgPXIndicator"] = 819;
	m_FixItems["NoEvents"] = 864;
	m_FixItems["EventType"] = 865;
	m_FixItems["NoInstAttrib"] = 870;
	m_FixItems["InstAttribType"] = 871;
	m_FixItems["InstAttribValue"] = 872;
	m_FixItems["LastRptRequest"] = 912;
	m_FixItems["HostCrossID"] = 961;
	m_FixItems["MinPriceIncrement"] = 969;
	m_FixItems["SecurityUpdateAction"] = 980;
	m_FixItems["UnitOfMeasure"] = 996;
	m_FixItems["MDFeedType"] = 1022;
	m_FixItems["ManualOrderIndicator"] = 1028;
	m_FixItems["CustOrderHandlingInst"] = 1031;
	m_FixItems["AggressorIndicator"] = 1057;
	m_FixItems["MaxTradeVol"] = 1140;
	m_FixItems["NoMdFeedTypes"] = 1141;
	m_FixItems["MatchAlgorithm"] = 1142;
	m_FixItems["MaxPriceVariation"] = 1143;
	m_FixItems["EventTime"] = 1145;
	m_FixItems["MinPriceIncrementAmount"] = 1146;
	m_FixItems["UnitOfMeasureQty"] = 1147;
	m_FixItems["LowLimitPrice"] = 1148;
	m_FixItems["HighLimitPrice"] = 1149;
	m_FixItems["TradingReferencePrice"] = 1150;
	m_FixItems["SecurityGroup"] = 1151;
	m_FixItems["ApplID"] = 1180;
	m_FixItems["Volatility"] = 1188;
	m_FixItems["ExpirationTimeValue"] = 1189;
	m_FixItems["RiskFreeRate"] = 1190;
	m_FixItems["NoLotTypeRules"] = 1234;
	m_FixItems["MarketSegmentID"] = 1300;
	m_FixItems["NoFills"] = 1362;
	m_FixItems["FillExecID"] = 1363;
	m_FixItems["FillPx"] = 1364;
	m_FixItems["FillQty"] = 1365;
	m_FixItems["EncryptedPasswordMethod"] = 1400;
	m_FixItems["EncryptedPasswordLen"] = 1401;
	m_FixItems["EncryptedPassword"] = 1402;
	m_FixItems["ClearingTradePriceType"] = 1598;
	m_FixItems["ApplicationSystemName"] = 1603;
	m_FixItems["ApplicationSystemVersion"] = 1604;
	m_FixItems["ApplicationSystemVendor"] = 1605;
	m_FixItems["FillYieldType"] = 1622;
	m_FixItems["AvgPxGroupID"] = 1731;
	m_FixItems["Memo"] = 5149;
	m_FixItems["ClearedVolume"] = 5791;
	m_FixItems["OpenInterestQty"] = 5792;
	m_FixItems["TradingReferenceDate"] = 5796;
	m_FixItems["MatchEventIndicator"] = 5799;
	m_FixItems["DecayStartDate"] = 5819;
	m_FixItems["DelayDuration"] = 5904;
	m_FixItems["RequestTime"] = 5979;
	m_FixItems["Asset"] = 6937;
	m_FixItems["SelfMatchPreventionID"] = 7928;
	m_FixItems["SelfMatchPreventionInstruction"] = 8000;
	m_FixItems["SplitMsg"] = 9553;
	m_FixItems["CtiCode"] = 9702;
	m_FixItems["OriginalSecondaryExecID"] = 9703;
	m_FixItems["GiveUpFirm"] = 9707;
	m_FixItems["CmtaGiveupCD"] = 9708;
	m_FixItems["CorrelationClOrdID"] = 9717;
	m_FixItems["OFMOverride"] = 9768;
	m_FixItems["NoProcessedEntries"] = 9772;
	m_FixItems["UserDefinedInstrument"] = 9779;
	m_FixItems["DisplayFactor"] = 9787;
	m_FixItems["MDTradeEntryID"] = 37711;
}

FixItems& FixItems::GetInstance()
{
	return m_Instance;
}

int FixItems::GetItemKey(std::string name)
{
	return m_FixItems[name];
}

