#ifndef __h_stepdef_h__
#define __h_stepdef_h__

#define		STEP_CODE			1			//错误代码
#define		STEP_MSG			2			//错误信息
#define		STEP_FUNC			3			//功能号
#define		STEP_SESSION			4			//会话号
#define		STEP_REQUESTNO			5			//请求编号
#define		STEP_RETURNNUM			6			//数据包记录数
#define		STEP_TOTALNUM			7			//总记录数
#define		STEP_JLXH			8			//记录序号
#define		STEP_QQQSJL			9			//请求起始记录
#define		STEP_QQFHJLS			10			//请求返回记录数
#define		STEP_QQFHZD			11			//请求返回的字段
#define		STEP_TXMY			12			//密钥
#define		STEP_XNZB			13			//性能指标
#define		STEP_RSZB			14			//服务器人数占比
#define		STEP_XTSJ			15			//服务器时间
#define		STEP_FWQZT			16			//服务器状态
#define		STEP_JGLB			40			//价格类型
#define		STEP_YXQLX			41			//有效期
#define		STEP_CJLLX			42			//成交量类型
#define		STEP_ZXCJL			43			//最小成交量
#define		STEP_KZZD			44			//扩展字段
#define		STEP_QFJZC			45			//区分今昨仓
#define		STEP_SCXX			45			//市场信息
#define		STEP_DWC			46			//定位串
#define		STEP_MYLB			47			//密钥类别
#define		STEP_KHH			50			//客户号
#define		STEP_ZJZH			51			//资金帐号
#define		STEP_GDH			52			//股东号
#define		STEP_ZHLB			53			//帐号类别
#define		STEP_SCDM			54			//市场代码
#define		STEP_SCMC			55			//市场名称
#define		STEP_HBDM			56			//货币代码
#define		STEP_HBDMMC			57			//货币代码名称
#define		STEP_JYMM			58			//交易密码
#define		STEP_ZJMM			59			//资金密码
#define		STEP_YHMM			60			//银行密码
#define		STEP_QSDM			61			//券商代码
#define		STEP_YYBDM			62			//营业部代码
#define		STEP_HYDM			63			//合约代码
#define		STEP_HYDMMC			64			//合约名称
#define		STEP_WTBH			65			//委托编号
#define		STEP_CJBH			66			//成交编号
#define		STEP_DLLB			67			//登录类别
#define		STEP_DTMMLB			68			//动态密码类别
#define		STEP_DTMM			69			//动态密码
#define		STEP_YPBH			70			//硬盘编号
#define		STEP_LOCAL_IP			71			//客户端本机IP地址
#define		STEP_LOCAL_MAC			72			//客户端MAC地址
#define		STEP_VERSION			73			//客户端版本号
#define		STEP_KHMC			74			//客户名称
#define		STEP_TRADE_DATE			75			//当前交易日
#define		STEP_LAST_TRADE_DATE			76			//上一交易日
#define		STEP_LAST_LOGIN_MAC			77			//上次登录MAC地址
#define		STEP_LAST_LOGIN_DATE			78			//上次登录日期
#define		STEP_LAST_LOGIN_TIME			79			//上次登录时间
#define		STEP_LAST_LOGIN_TYPE			80			//上次登录方式
#define		STEP_LOGIN_INFO			81			//登录提示信息
#define		STEP_QZZHQR			82			//强制帐号确认
#define		STEP_SERVER_VERSION			83			//网关版本号
#define		STEP_XTZT			84			//系统状态
#define		STEP_XTZTMC			85			//系统状态名称
#define		STEP_LOGIN_FLAG			86			//登录标志
#define		STEP_XGMMTS			87			//修改密码提示信息
#define		STEP_ZC_ZJZH			88			//证券资金帐号
#define		STEP_RISK_VERSION			89			//风险提示书版本号
#define		STEP_YLXX			90			//预留信息
#define		STEP_ZJYE			91			//资金余额
#define		STEP_QCYE			92			//期初余额
#define		STEP_KYZJ			93			//可用资金
#define		STEP_DJZJ			94			//冻结资金
#define		STEP_KQZJ			95			//可取资金
#define		STEP_ZSZ			96			//总市值
#define		STEP_ZZC			97			//总资产(当前权益)
#define		STEP_ZJZCZZ			98			//资金资产总值
#define		STEP_QCQY			99			//上日权益(期初权益)
#define		STEP_CCFDYK			101			//持仓浮动盈亏
#define		STEP_PCFDYK			102			//平仓浮动盈亏
#define		STEP_CCDSYK			103			//持仓盯市盈亏
#define		STEP_PCDSYK			104			//平仓盯市盈亏
#define		STEP_CCSXF			105			//手续费
#define		STEP_ZYJE			106			//质押金额
#define		STEP_JYSSSFXD			107			//交易所风险度(实时)
#define		STEP_FXLB			108			//风险类别
#define		STEP_FXLBMC			109			//风险类别名称
#define		STEP_XJZC			110			//现金资产
#define		STEP_KYBZJ			111			//可用保证金
#define		STEP_MMLB			112			//买卖类别
#define		STEP_CJSL			113			//成交数量
#define		STEP_CJJG			114			//成交价格
#define		STEP_QSMC			115			//券商名称
#define		STEP_CJSJ			116			//成交时间
#define		STEP_KPBZ			117			//开平仓标志
#define		STEP_KPBZMC			118			//开平仓名称
#define		STEP_TBBZ			119			//投保标志
#define		STEP_WTXTH			120			//委托系统号
#define		STEP_BDDM			121			//标的代码
#define		STEP_BDMC			122			//标的名称
#define		STEP_QQHYZH			123			//期权合约帐号
#define		STEP_QQHYBZ			124			//期权合约标识
#define		STEP_BDBZ			125			//期权备兑标志
#define		STEP_BDBZMC			126			//备兑标志名称
#define		STEP_SJWTLB			127			//市价委托类别
#define		STEP_SJWTLBMC			128			//市价委托名称
#define		STEP_WTJG			129			//委托价格
#define		STEP_WTSL			130			//委托数量
#define		STEP_HYLB			131			//合约类别
#define		STEP_HYDMQC			132			//期权代码全称
#define		STEP_CJJE			133			//成交金额
#define		STEP_MMLBSM			134			//买卖类别说明
#define		STEP_DQSL			135			//当前数量
#define		STEP_MRJJ			136			//买入均价
#define		STEP_KYSL			137			//可用数量
#define		STEP_ZXJ			138			//最新价
#define		STEP_CBJ			139			//成本价
#define		STEP_BBJ			140			//保本价
#define		STEP_FDYK			141			//浮动盈亏
#define		STEP_ZQSZ			142			//证券市值
#define		STEP_LJYK			143			//累计盈亏
#define		STEP_CCCB			144			//持仓成本额
#define		STEP_DJSL			145			//冻结数量
#define		STEP_WJSSL			146			//未交收数量
#define		STEP_KCRQ			147			//开仓日期
#define		STEP_MRJE			148			//买入金额
#define		STEP_MCJE			149			//卖出金额
#define		STEP_LXBJ			150			//利息报价
#define		STEP_FLTSL			151			//非流通数量
#define		STEP_BZJ			152			//保证金
#define		STEP_JKCCCL			153			//今开仓持仓量
#define		STEP_JPCCCL			154			//今平仓持仓量
#define		STEP_JPCWTL			155			//今平仓委托量
#define		STEP_WTZT			156			//委托状态
#define		STEP_WTZTMC			157			//委托状态名称
#define		STEP_CDSL			158			//撤单数量
#define		STEP_WTSJ			159			//委托时间
#define		STEP_WTRQ			160			//委托日期
#define		STEP_XWH			161			//席位号
#define		STEP_XDXW			162			//下单席位
#define		STEP_BZXX			163			//备注信息
#define		STEP_XDYY			164			//下单原因
#define		STEP_CJSX			165			//成交属性
#define		STEP_NEWMM			166			//新密码
#define		STEP_PWDTYPE			167			//密码类别
#define		STEP_ZZHBZ			168			//主帐号标志
#define		STEP_ZHSX			169			//账号属性
#define		STEP_QSRQ			171			//起始日期
#define		STEP_ZZRQ			172			//终止日期
#define		STEP_CJRQ			173			//成交日期
#define		STEP_JGBZ			174			//交割标志
#define		STEP_JGXH			175			//交割序号
#define		STEP_CJHSL			176			//成交后数量
#define		STEP_QSJE			177			//清算金额
#define		STEP_CJHZJYE			178			//成交后资金余额
#define		STEP_YJ			179			//佣金
#define		STEP_YHS			180			//印花税
#define		STEP_GHF			181			//过户费
#define		STEP_SXF			182			//手续费
#define		STEP_ZGF			183			//证管费
#define		STEP_QSF			184			//清算费
#define		STEP_QTFY			185			//其它费
#define		STEP_JSSLB			186			//揭示书类别
#define		STEP_JSSBB			187			//揭示书版本
#define		STEP_JSSNR			188			//揭示书内容
#define		STEP_XXNRGS			189			//消息内容格式
#define		STEP_XXNR			190			//消息内容
#define		STEP_ZRYE			191			//资金昨日余额
#define		STEP_ZJKYJE			192			//资金可用金额
#define		STEP_ZJDJJE			193			//资金冻结金额
#define		STEP_ZJJDJE			194			//资金解冻金额
#define		STEP_JYDJJE			195			//资金交易冻结金额
#define		STEP_JYJDJE			196			//资金交易解冻金额
#define		STEP_JYZTJE			197			//资金交易在途金额三
#define		STEP_ZCJE			198			//资金交易轧差金额
#define		STEP_ZJZT			199			//资金状态
#define		STEP_LSXH			200			//流水序号
#define		STEP_JSRQ			201			//清算日期
#define		STEP_FSRQ			202			//发生日期
#define		STEP_FSSJ			203			//发生时间
#define		STEP_CGZH			205			//存管账户
#define		STEP_YZYWBZ			206			//银证业务标识
#define		STEP_YZYWSM			207			//银证业务标识说明
#define		STEP_YWDM			208			//业务代码
#define		STEP_YWJE			209			//业务金额
#define		STEP_YZYWZT			210			//银证业务状态
#define		STEP_YZYWZTSM			211			//银证业务状态说明
#define		STEP_SCCL			212			//客户端上传策略
#define		STEP_INITFLAG			213			//初始化标志
#define		STEP_YHZH			214			//银行账号
#define		STEP_YHBM			215			//银行编码
#define		STEP_YHMC			216			//银行名称
#define		STEP_YECXMMBZ			217			//银行余额查询银行密码标志
#define		STEP_ZJMMBZ			218			//券转银资金密码标志
#define		STEP_YHMMBZ			219			//银转券银行密码标志
#define		STEP_ZZJE			220			//转账金额
#define		STEP_YZLSH			221			//银证流水号
#define		STEP_FHXX			222			//返回信息
#define		STEP_TSLB			223			//推送类别
#define		STEP_YHYE			224			//银行余额
#define		STEP_NEWYHMM			225			//新的银行密码
#define		STEP_JGSM			226			//结果说明
#define		STEP_SQRQ			227			//转帐日期或申请日期
#define		STEP_SQSJ			228			//转帐时间或者申请时间
#define		STEP_JSDCXLB			229			//结算单查询类别（期货）
#define		STEP_XQSL			230			//行权数量
#define		STEP_XYBH			231			//协议编号
#define		STEP_TZXH			232			//通知序号
#define		STEP_FXBSLB			233			//风险标识类别
#define		STEP_FXBSMC			234			//风险标识名称
#define		STEP_TZCJRQ			235			//创建日期
#define		STEP_TZCJSJ			236			//创建时间
#define		STEP_TZQDLB			237			//通知渠道类别
#define		STEP_TZQDMC			238			//通知渠道名称
#define		STEP_TZFSRQ			239			//发送日期
#define		STEP_TZFSSJ			240			//发送时间
#define		STEP_FKBZ			241			//反馈标志
#define		STEP_FKBZMC			242			//反馈标志名称
#define		STEP_TZNR			243			//通知内容
#define		STEP_HYCS			244			//合约乘数
#define		STEP_ZXBDJW			245			//最小变动价位
#define		STEP_WTSX			246			//限价单最大下单量
#define		STEP_ZCSX			247			//市价单最大下单量
#define		STEP_JYRQ			248			//交易日期
#define		STEP_DLZH			249			//登录帐号
#define		STEP_KMSL			250			//可委托数量
#define		STEP_XXLB			251			//消息类别
#define		STEP_SDFX			252			//锁定方向
#define		STEP_OLDMM			253			//修改密码的老密码
#define		STEP_CP			254			//产品
#define		STEP_PT			255			//平台
#define		STEP_JJSMC			256			//经纪商名称
#define		STEP_LAST_LOGIN_IP			257			//上一次登录的IP地址
#define		STEP_LAST_LOGIN_TIMES			258			//上一次登录的次数
#define		STEP_KHJB			259			//客户级别
#define		STEP_FJYSQLB			261			//非交易申请类别
#define		STEP_KXQSL			262			//可行权数量
#define		STEP_SBSJ			263			//申报时间
#define		STEP_FJYSQLBMC			264			//非交易申请类别名称
#define		STEP_JYLB			265			//交易类别
#define		STEP_ZQGFYE			266			//昨日股份余额
#define		STEP_KSDSL			267			//可锁定数量
#define		STEP_KJSSL			268			//可解锁数量
#define		STEP_XQJG			269			//行权价格
#define		STEP_MMLBMC			270			//买卖名称
#define		STEP_BDJFSL			271			//标的券收付数量
#define		STEP_JSJE			272			//结算金额
#define		STEP_XQLB			273			//行权策略类别
#define		STEP_XQCLZ			274			//行权策略值
#define		STEP_XQKZKG			275			//行权控制开关
#define		STEP_QQXQR			276			//期权行权日
#define		STEP_HQZH			277			//行情帐号
#define		STEP_HQMM			278			//行情密码
#define		STEP_TZZMC			279			//投资者名称
#define		STEP_DWBZJ			280			//单位保证金
#define		STEP_SJHM			281			//手机号码
#define		STEP_WJBZ			282			//文件标识
#define		STEP_MD5			283			//MD5码
#define		STEP_WJNR			284			//文件内容
#define		STEP_QLJ			285			//权利金
#define		STEP_BDKYGF			286			//备兑可用股份
#define		STEP_BDKYYE			287			//备兑可用余额
#define		STEP_XQCLYXJB			288			//行权策略优先级别
#define		STEP_BDLB			289			//标的类别
#define		STEP_YXJBSM			300			//行权策略优先级别说明
#define		STEP_BDGFKY			301			//备兑股份可用
#define		STEP_BDGFYE			302			//备兑股份余额
#define		STEP_XYLX			303			//协议类型
#define		STEP_XYBB			304			//协议版本
#define		STEP_DZXYLB			305			//电子协议类别
#define		STEP_XYZTMC			306			//协议状态名称
#define		STEP_QDMC			307			//操作渠道名称
#define		STEP_CZZD			308			//操作站点
#define		STEP_ZJLXMC			309			//证件类型名称
#define		STEP_ZJHM			310			//证件号码
#define		STEP_QSJGDM			311			//签署机构代码
#define		STEP_QSLX			312			//签署类型
#define		STEP_QSSJ			313			//签署时间
#define		STEP_SXRQ			314			//生效日期
#define		STEP_YXRQ			315			//有效日期
#define		STEP_ZXRQ			316			//注销日期
#define		STEP_ZXSJ			317			//注销时间
#define		STEP_XYZT			318			//协议状态
#define		STEP_BZJQK			319			//保证金缺口
#define		STEP_MRED			320			//买入额度
#define		STEP_DQBZJL			321			//当前保证金率（按金额）
#define		STEP_DQBZJJE			322			//当前保证金金额
#define		STEP_KCSXF1			323			//开仓手续费按手数
#define		STEP_KCSXF2			324			//开仓手续费按金额
#define		STEP_PCSXF3			325			//平仓手续费按手数
#define		STEP_PCSXF4			326			//平仓手续费按金额
#define		STEP_XQSXF5			327			//行权手续费率按手数
#define		STEP_XQSXF6			328			//行权手续费率按金额
#define		STEP_KZXCSL			329			//看涨限仓数量
#define		STEP_KDXCSL			330			//看跌限仓数量
#define		STEP_BDDMLB			331			//标的证券类别
#define		STEP_QSSL			332			//清算数量
#define		STEP_JSSL			333			//交收数量
#define		STEP_QKSL			334			//缺口数量
#define		STEP_CZSL			335			//处置数量
#define		STEP_FHSL			336			//返还数量
#define		STEP_QKZJ			337			//缺口资金
#define		STEP_FHJE			338			//返还金额
#define		STEP_TZJE			339			//调账金额
#define		STEP_FZLX			340			//负债类型
#define		STEP_FZMC			341			//负债名称
#define		STEP_IMEI1			342			//手机协议IMEI取消
#define		STEP_JYSFXD_NEW			343			//对冲风险度
#define		STEP_BROKER			344			//期货公司名称
#define		STEP_GSSSFXD			345			//风险度-公司的
#define		STEP_ZYBZJ			346			//占用保证金
#define		STEP_KQBZ			347			//查询可取资金
#define		STEP_TBBZMC			348			//投保标志名称
#define		STEP_HXRZ			349			//核心认证类别
#define		STEP_HXMM			350			//核心认证密码
#define		STEP_CPU			351			//CPU
#define		STEP_ZBRQ			352			//主板日期
#define		STEP_YHFZXDM			353			//银行分中心代码
#define		STEP_QPBZ			354			//强平标志
#define		STEP_HQDXKL			355			//获取短信口令标志
#define		STEP_DXTSXX			356			//短信口令返回提示信息
#define		STEP_DXYZM			357			//短信验证码
#define		STEP_CKDXKL			358			//验证短信口令
#define		STEP_DTLPYXQ			359			//动态令牌有效期
#define		STEP_JSD			360			//结算单
#define		STEP_GSFXD			361			//公司风险度
#define		STEP_QRBZ			362			//结算单确认标志
#define		STEP_XYJYR			363			//下一交易日
#define		STEP_PZDM			364			//品种代码
#define		STEP_PZMC			365			//品种名称
#define		STEP_KCZL			366			//库存总量
#define		STEP_KYKC			367			//可用库存
#define		STEP_DTKC			368			//待提库存
#define		STEP_JMRL			369			//今买入量
#define		STEP_JMCL			370			//今卖出量
#define		STEP_JCR			371			//今存入
#define		STEP_JTC			372			//今提出
#define		STEP_JJR			373			//今借入
#define		STEP_JJC			374			//今借出
#define		STEP_CKL			375			//出库量
#define		STEP_XHDJKC			376			//现货冻结库存
#define		STEP_ZYKC			377			//质押库存
#define		STEP_ZYDJKC			378			//质押冻结库存
#define		STEP_FLDJKC			379			//法律冻结库存
#define		STEP_YHDJKC			380			//银行冻结库存
#define		STEP_KCJJ			381			//库存均价
#define		STEP_FSJE			382			//发生金额
#define		STEP_LSH			383			//流水号
#define		STEP_HZFX			384			//划转方向
#define		STEP_HZFXMC			385			//划转方向名称
#define		STEP_HZZTMC			386			//划转状态名称
#define		STEP_CZLY			387			//操作来源
#define		STEP_CLZT			388			//处理状态
#define		STEP_JYLX			389			//黄金交易类型
#define		STEP_HZJE			390			//划转金额
#define		STEP_CXZJLB			392			//查询可划拨资金
#define		STEP_KHBZJ			393			//可划拨资金
#define		STEP_ZJHBBZ			394			//资金划拨标志
#define		STEP_HZJYE			395			//后资金余额
#define		STEP_CKEDXZ			396			//存款额度限制
#define		STEP_QKEDXZ			397			//取款额度限制
#define		STEP_YYRQ			398			//预约日期
#define		STEP_CSDM			399			//城市代码
#define		STEP_CSMC			400			//城市名称
#define		STEP_CKDM			401			//仓库代码
#define		STEP_CKMC			402			//仓库名称
#define		STEP_CKDZ			403			//仓库地址
#define		STEP_LXR			404			//联系人
#define		STEP_THZL			405			//提货重量
#define		STEP_THMM			406			//提货密码
#define		STEP_ZJLX			407			//证件类型
#define		STEP_THMS			409			//提货密码
#define		STEP_THDH			410			//提货单号
#define		STEP_YHTHR			411			//银行提货日
#define		STEP_THZTMC			412			//提货状态名称
#define		STEP_THR			413			//提货人
#define		STEP_LXDH			414			//联系电话
#define		STEP_WTFS			415			//委托方式
#define		STEP_ZHMC			416			//账户类型名称
#define		STEP_ZHHM			417			//账户号码
#define		STEP_KHZT			418			//客户状态
#define		STEP_YWMC			419			//业务名称
#define		STEP_DXTZ			420			//短信通知
#define		STEP_YWBZ			421			//业务标志
#define		STEP_YWLX			422			//业务类型
#define		STEP_BZYJ			423			//标准佣金
#define		STEP_FY3			424			//费用3
#define		STEP_FYX			425			//费用X
#define		STEP_FARE1			426			//一级总费用
#define		STEP_FARE2			427			//一级经手费
#define		STEP_FARE3			428			//一级印花税
#define		STEP_FARE4			429			//一级过户费
#define		STEP_FARE5			430			//一级证管费
#define		STEP_FARE6			431			//一级规费
#define		STEP_FARE7			432			//一级手续费
#define		STEP_FXJ			433			//风险金
#define		STEP_XQGHF			434			//行权过户费
#define		STEP_JSF			435			//其他费(结算费)
#define		STEP_SCLX			436			//市场类型
#define		STEP_XQDJZJ			437			//行权冻结资金
#define		STEP_XQSDBZJ			438			//行权锁定保证金
#define		STEP_TZJE2			439			//透支金额
#define		STEP_YJFX			440			//预计罚息
#define		STEP_SRCCYE			441			//上日持仓余额
#define		STEP_CRJ			442			//出入金
#define		STEP_DJSXF			443			//冻结手续费
#define		STEP_BROKER_ID			444			//期货所用的BrokerID
#define		STEP_UNIQUE_ID			445			//客户端唯一识别码
#define		STEP_DRCRJ			446			//当日出入金
#define		STEP_DRQLJSR			447			//当日权利金收入
#define		STEP_ZBZJ			448			//总保证金
#define		STEP_MRBZJ			449			//买入保证金
#define		STEP_DRQLJZC			450			//当日权利金支出
#define		STEP_ZJYSBZJ			451			//总交易所保证金
#define		STEP_MCCSBZJ			452			//卖出初始保证金
#define		STEP_JYDJQLJ			453			//交易冻结权利金
#define		STEP_ZXDJBZJ			454			//执行冻结保证金
#define		STEP_MCDJCSBZJ			455			//卖出冻结初始保证金
#define		STEP_ZJFYDJJE			456			//资金费用冻结金额
#define		STEP_CCZYK			457			//持仓总盈亏
#define		STEP_WTDJJE			458			//委托冻结金额
#define		STEP_JDJE			459			//解冻金额
#define		STEP_ZCZH			460			//资产账号
#define		STEP_HYJC			461			//合约简称
#define		STEP_HYZRYE			462			//合约昨日余额
#define		STEP_HYYE			463			//合约余额
#define		STEP_WCBZJ			464			//维持保证金
#define		STEP_BDGFSL			465			//备兑股份数量
#define		STEP_MRCB			466			//合约买入成本
#define		STEP_JCSJ			467			//建仓时间
#define		STEP_DJBZJ			468			//冻结保证金
#define		STEP_JDBZJ			469			//解冻保证金
#define		STEP_JYGF			470			//交易规费
#define		STEP_JSXF			471			//净手续费
#define		STEP_ZFY			472			//总费用
#define		STEP_YWSM			473			//业务说明
#define		STEP_HYLBMC			474			//合约类别名称
#define		STEP_XGED_SH			475			//上海限购额度
#define		STEP_XGED_SZ			476			//深圳限购额度
#define		STEP_SYED_SH			477			//上海剩余额度
#define		STEP_SYED_SZ			478			//深圳剩余额度
#define		STEP_KHDBZW			479			//客户端标志位
#define		STEP_TXBZ			480			//提醒标志
#define		STEP_TXNR			481			//提醒内容
#define		STEP_SJJG			482			//市价价格
#define		STEP_XQYFSL			483			//行权应付数量
#define		STEP_XQYFJE			484			//行权应付金额
#define		STEP_YPFQ			485			//硬盘分区
#define		STEP_JSJM			486			//计算机名
#define		STEP_CJJJ			487			//成交均价
#define		STEP_KJYLX			488			//可交易类型
#define		STEP_YZFS			489			//手机认证方式
#define		STEP_TZZZH			490			//投资者帐号
#define		STEP_MYBH			491			//密钥编号
#define		STEP_DTMY			492			//动态密钥
#define		STEP_SRJE			493			//收入金额
#define		STEP_FCJE			494			//付出金额
#define		STEP_CFTJ			495			//触发条件
#define		STEP_ZSJG			496			//止损价格
#define		STEP_ZBFY			497			//逐笔浮盈
#define		STEP_ZRFY			498			//逐日浮盈
#define		STEP_ZJSJ			499			//昨结算价
#define		STEP_CZBZ			500			//操作标识
#define		STEP_GDJG			501			//改单价格
#define		STEP_GDSL			502			//改单数量
#define		STEP_CCRQ			503			//持仓日期
#define		STEP_CJF			504			//成交费
#define		STEP_CCDCYK			505			//持仓对冲盈亏
#define		STEP_DCPCYK			506			//对冲平仓盈亏
#define		STEP_PCL			507			//持仓明细中的平仓量
#define		STEP_FSSL			508			//发生数量
#define		STEP_HZQSL			509			//后证券数量
#define		STEP_DBFX			510			//调拨方向
#define		STEP_DBFXMC			511			//调拨方向名称
#define		STEP_ZQDM			512			//证券代码
#define		STEP_ZQMC			513			//证券名称
#define		STEP_CJZL			514			//成交重量
#define		STEP_QPMC			515			//强平名称
#define		STEP_CDSJ			516			//撤单时间
#define		STEP_WTZL			517			//委托重量
#define		STEP_HYSZ			518			//合约市值
#define		STEP_JYSGFH			519			//交易所过户费
#define		STEP_XQRQ			520			//行权开始日期
#define		STEP_XQDQRQ			521			//行权到期日期
#define		STEP_GPBZ			522			//挂牌标志
#define		STEP_LJDQ			523			//临近到期
#define		STEP_ZSPJ			524			//昨收盘价
#define		STEP_TZBZ			525			//调整标志
#define		STEP_QQZXFS			526			//期权执行方式
#define		STEP_HYQSPJ			527			//合约前收盘价
#define		STEP_JYBK			528			//交易板块
#define		STEP_ZQZH			529			//证券帐号
#define		STEP_ZHJB			530			//账号级别
#define		STEP_ZHZTMC			531			//账号状态名称
#define		STEP_ZJMC			532			//证件名称
#define		STEP_ZYMRED			534			//占用买入额度
#define		STEP_NBJG			535			//内部机构
#define		STEP_SRZJYE			536			//上日资金余额
#define		STEP_HYXGSL			537			//合约新挂数量
#define		STEP_HYTZSL			538			//合约调整数量
#define		STEP_HYTPSL			539			//合约停牌数量
#define		STEP_HYZPSL			540			//合约摘牌数量
#define		STEP_XGED			541			//限购额度
#define		STEP_SQLX			542			//申请类型
#define		STEP_SQMC			543			//申请名称
#define		STEP_SQZT			544			//申请状态
#define		STEP_SQZTMC			545			//申请状态名称
#define		STEP_SQED			546			//申请额度
#define		STEP_SPED			547			//审批额度
#define		STEP_ZQLBMC			548			//证券类别名称
#define		STEP_ZQLB			549			//证券类别
#define		STEP_BDSDSL			550			//备兑锁定数量
#define		STEP_BDQKSL			551			//备兑缺口数量
#define		STEP_YGQKSL			552			//备兑预估缺口数量
#define		STEP_BDZT			553			//标的状态
#define		STEP_BDZTMC			554			//标的状态名称
#define		STEP_SSBZ			556			//申赎标志
#define		STEP_HBSL			557			//划拨数量
#define		STEP_CFBZ			558			//拆分标志
#define		STEP_SZED			559			//客户新股申购市值额度
#define		STEP_QSPH			560			//起始配号
#define		STEP_PHSL			561			//配号数量
#define		STEP_SGJG			562			//申购价格
#define		STEP_SGSX			563			//申购上限
#define		STEP_SGXX			564			//申购下限
#define		STEP_FXRQ			565			//发行日期
#define		STEP_CPLX			566			//测评类型
#define		STEP_DA			567			//答案
#define		STEP_FS			568			//分数
#define		STEP_TMMZ			569			//题目名字
#define		STEP_TH			570			//题号
#define		STEP_PJBT			571			//评价标题
#define		STEP_PJDJ			572			//评价等级
#define		STEP_FXGZ			573			//风险估值
#define		STEP_PJMC			574			//评价名称
#define		STEP_GXRQ			575			//更新日期
#define		STEP_PJLX			576			//风险评价类型
#define		STEP_ZQSL			578			//中签数量
#define		STEP_YJSL			579			//已缴数量
#define		STEP_DZRQ			580			//到账日期
#define		STEP_RGRQ			581			//认购日期
#define		STEP_FXJG			582			//发行价格
#define		STEP_FQSL			583			//放弃数量
#define		STEP_DBZT			585			//担保状态
#define		STEP_DBZTMC			586			//担保状态名称
#define		STEP_FDBL			587			//浮动比例
#define		STEP_ZSBL			588			//折算比例
#define		STEP_RZSL			589			//融资数量
#define		STEP_RZJE			590			//融资金额
#define		STEP_RQSL			591			//融券数量
#define		STEP_RQJE			592			//融券金额
#define		STEP_DRRZWTSL			593			//当日融资委托数量
#define		STEP_DRRZWTJE			594			//当日融资委托金额
#define		STEP_DRRQWTSL			595			//当日融券委托数量
#define		STEP_DRRQWTJE			596			//当日委托融券金额
#define		STEP_DRRZCJSL			597			//当日融资成交数量
#define		STEP_DRRZCJJE			598			//当日融资成交金额
#define		STEP_DRRQCJSL			599			//当日融券成交数量
#define		STEP_DRRQCJJE			600			//当日融券成交金额
#define		STEP_FZJE			601			//负债金额
#define		STEP_FZSL			602			//负债数量
#define		STEP_FZLX2			603			//负债利息
#define		STEP_FZLL			604			//负债利率
#define		STEP_HKBJ			605			//已经还款本金
#define		STEP_HKLX			606			//已经还款利息
#define		STEP_HQSL			607			//已经还券数量
#define		STEP_FZZT			608			//负债状态
#define		STEP_FZZTMC			609			//负债状态名称
#define		STEP_JZRQ			610			//截止日期
#define		STEP_ZJHKRQ			611			//最近还券还款日期
#define		STEP_ZJHKJE			612			//直接还款金额
#define		STEP_QSBZ			613			//清算标志
#define		STEP_YKJE			614			//盈亏金额
#define		STEP_FLTSZ			615			//非流通市值
#define		STEP_HZLB			616			//划转类别
#define		STEP_HZSL			617			//划转数量
#define		STEP_HKJE			618			//还款金额
#define		STEP_FZRQ			619			//负债日期
#define		STEP_DBZC			620			//担保资产
#define		STEP_ZFZ			621			//总负债
#define		STEP_RZYE			623			//融资余额
#define		STEP_RQYE			624			//融券余额
#define		STEP_KHKJE			625			//可还款金额
#define		STEP_JYXW			626			//交易行为
#define		STEP_RQSZ			627			//融券市值
#define		STEP_RZHYYK			628			//融资合约盈亏
#define		STEP_RQYK			629			//融券盈亏
#define		STEP_JZC			630			//净资产
#define		STEP_QHZDC			633			//期权行权后期货自动自动对冲
#define		STEP_XJBH			634			//询价编号
#define		STEP_XJZT			635			//询价状态
#define		STEP_RZBZ			636			//融资标志
#define		STEP_RZBZMC			637			//融资允许标志名称
#define		STEP_RQBZ			638			//融券标志
#define		STEP_RQBZMC			639			//融券允许标志名称
#define		STEP_ZSXS			640			//折算系数
#define		STEP_RZBL			642			//融资比例
#define		STEP_RQBL			643			//融券比例
#define		STEP_GSZSL			644			//公司折算率
#define		STEP_RZBZJBL			645			//融资保证金比例(执行)
#define		STEP_RQBZJBL			646			//融券保证金比例(执行)
#define		STEP_RGDM			647			//认购代码
#define		STEP_RGSL			648			//认购数量
#define		STEP_ZHDM			649			//转换代码
#define		STEP_JYSCJBH			650			//交易所成交编号
#define		STEP_ZQSC			651			//证券市场
#define		STEP_JJGS			652			//基金公司
#define		STEP_JJDM			653			//基金代码
#define		STEP_JJZH			654			//基金账户
#define		STEP_SFFS			655			//收费方式
#define		STEP_WTJE			656			//委托金额
#define		STEP_FHFS			657			//分红方式
#define		STEP_JJMC			658			//基金名称
#define		STEP_JYJE			659			//交易金额
#define		STEP_JJGSMC			660			//基金公司名称
#define		STEP_JJJZ			661			//基金净值
#define		STEP_JJFXDJ			663			//基金风险等级
#define		STEP_ZDXE			664			//最低限额
#define		STEP_ZDJE			665			//最低金额
#define		STEP_JESHBZ			667			//巨额赎回标志
#define		STEP_THBH			668			//提货编号
#define		STEP_FHFSMC			669			//分红方式名称
#define		STEP_SFFSMC			670			//收费方式名称
#define		STEP_RZFZ			671			//融资负债
#define		STEP_FXCPBZ			672			//风险测评标志
#define		STEP_FXCPFS			673			//风险测评方式
#define		STEP_DRXJCS			674			//当日询价次数
#define		STEP_XJCSSX			675			//询价次数上限
#define		STEP_MFXJCS			676			//免费询价次数
#define		STEP_PCH			677			//批次号
#define		STEP_GXSJ			678			//更新时间
#define		STEP_DRWTGXSJ			679			//当日委托更新时间
#define		STEP_DRCJGXSJ			680			//当日成交更新时间
#define		STEP_CCGXSJ			681			//持仓更新时间
#define		STEP_ZJGXSJ			682			//资金更新时间
#define		STEP_WTZHLX			683			//组合类型
#define		STEP_WCJSL			684			//未成交数量
#define		STEP_XJZTMC			685			//询价状态名称
#define		STEP_HQBZ			686			//获取数据更新时间标志
#define		STEP_XGCBJ			687			//修改成本价
#define		STEP_ZTMS			688			//主推模式
#define		STEP_SCLB			689			//市场列表
#define		STEP_ZYZJ			690			//占用资金
#define		STEP_BDDJ			691			//报单冻结
#define		STEP_DRSXF			692			//当日手续费
#define		STEP_ZMJC			693			//账面价差
#define		STEP_DRPCYK			694			//当日平仓盈亏
#define		STEP_RZZJ			695			//融资资金
#define		STEP_TZZJ			696			//调整资金
#define		STEP_FKDJ			697			//风控冻结
#define		STEP_DKDJ			698			//贷款冻结
#define		STEP_DRRJ			699			//当日入金
#define		STEP_DRCJ			700			//当日出金
#define		STEP_JTQY			701			//静态权益
#define		STEP_DTQY			702			//动态权益
#define		STEP_YSBZJ			703			//应收保证金
#define		STEP_CDBZJ			704			//冲抵保证金
#define		STEP_DCZJ			705			//待出资金
#define		STEP_YYJE			706			//预约额度
#define		STEP_YYCJRQ			707			//预约出金日期
#define		STEP_YYCJJE			708			//预约出金金额
#define		STEP_DRCJZE			709			//当日出金总额
#define		STEP_SYCJZE			710			//剩余出金总额
#define		STEP_MRCJED			711			//默认出金额度
#define		STEP_DSED			712			//待审额度
#define		STEP_YYDJED			713			//预约冻结额度
#define		STEP_KCCB			714			//开仓成本
#define		STEP_HJDM			715			//ETF黄金代码
#define		STEP_HJMC			716			//ETF黄金名称
#define		STEP_MFZL			717			//每份黄金重量
#define		STEP_ZXSGZL			718			//最小申购重量
#define		STEP_HYDM1			719			//认购或者申购第一个标的代码
#define		STEP_HYDM2			720			//认购或者申购第二个标的代码
#define		STEP_HYDM3			721			//认购或者申购第三个标的代码
#define		STEP_HYDM4			722			//认购或者申购第四个标的代码
#define		STEP_HYDM5			723			//认购或者申购第五个标的代码
#define		STEP_ZL1			724			//第一个标的重量
#define		STEP_ZL2			725			//第二个标的重量
#define		STEP_ZL3			726			//第三个标的重量
#define		STEP_ZL4			727			//第四个标的重量
#define		STEP_ZL5			728			//第五个标的重量
#define		STEP_ZZL			729			//总重量
#define		STEP_JYSWTBH			730			//交易所委托编号
#define		STEP_SSLB			731			//申赎类别
#define		STEP_WTMC			732			//委托名称
#define		STEP_TGDY			734			//托管单元
#define		STEP_JJLX			735			//基金类型
#define		STEP_SXFL			736			//手续费率
#define		STEP_SSMC			737			//申述名称
#define		STEP_YYED			738			//预约额度
#define		STEP_QKJE			739			//取款金额
#define		STEP_XJHKKYZJ			740			//现金还款可用资金
#define		STEP_MQHQKYZJ			741			//买券还券可用资金
#define		STEP_JZCBZ			742			//今昨仓标志
#define		STEP_GHJE			743			//归还金额
#define		STEP_RQFY			744			//融券费用
#define		STEP_RQLX			745			//融券利息
#define		STEP_TZRQ			746			//调整日期
#define		STEP_KCJEBL			747			//开仓金额比例
#define		STEP_PCJEBL			748			//平仓金额比例
#define		STEP_PJJEBL			749			//平今金额比例
#define		STEP_KCDWJE			750			//开仓单位金额
#define		STEP_PCDWJE			751			//平仓单位金额
#define		STEP_PJDWJE			752			//平今单位金额
#define		STEP_PZLB			753			//品种类别
#define		STEP_DQR			754			//到期日
#define		STEP_DBYH			756			//单边保证金优惠
#define		STEP_ZHCLBM			757			//组合策略编码
#define		STEP_ZHCLMC			758			//组合策略名称
#define		STEP_DQRXTBZ			759			//到期日是否相同
#define		STEP_BDZQXTBZ			760			//标的证券是否相同
#define		STEP_HYDMXTBZ			761			//合约单位是否相同
#define		STEP_HYGL			762			//合约个数
#define		STEP_DQCFTS			763			//组合到期提前拆分天数
#define		STEP_ZHCLLX			764			//组合策略类型
#define		STEP_HYLB_LEG1			765			//第一腿合约类别
#define		STEP_MMLB_LEG1			766			//第一腿持仓方向
#define		STEP_JGSX_LEG1			767			//第一腿合约行权价格顺序
#define		STEP_HYSL_LEG1			768			//第一腿合约数量
#define		STEP_HYLB_LEG2			769			//第二腿合约类别
#define		STEP_MMLB_LEG2			770			//第二腿持仓方向
#define		STEP_JGSX_LEG2			771			//第二腿合约行权价格顺序
#define		STEP_HYSL_LEG2			772			//第二腿合约数量
#define		STEP_HYLB_LEG3			773			//第三腿合约类别
#define		STEP_MMLB_LEG3			774			//第三腿持仓方向
#define		STEP_JGSX_LEG3			775			//第三腿合约行权价格顺序
#define		STEP_HYSL_LEG3			776			//第三腿合约数量
#define		STEP_HYLB_LEG4			777			//第四腿合约类别
#define		STEP_MMLB_LEG4			778			//第四腿持仓方向
#define		STEP_JGSX_LEG4			779			//第四腿合约行权价格顺序
#define		STEP_HYSL_LEG4			780			//第四腿合约数量
#define		STEP_ZHBH			781			//组合编号
#define		STEP_WTCFSL			782			//委托拆分数量
#define		STEP_ZHCLBZJ			783			//组合策略已用保证金
#define		STEP_ZHFX			784			//组合方向
#define		STEP_ZHFXMC			785			//组合方向名称
#define		STEP_CFHY1			786			//成份合约1
#define		STEP_CFHY2			787			//成份合约2
#define		STEP_CFHY3			788			//成份合约3
#define		STEP_CFHY4			789			//成份合约4
#define		STEP_CJFY			790			//成交费用
#define		STEP_CFHYMC1			791			//成份合约名称1
#define		STEP_CFHYMC2			792			//成份合约名称2
#define		STEP_CFHYMC3			793			//成份合约名称3
#define		STEP_CFHYMC4			794			//成份合约名称4
#define		STEP_JYPT			795			//交易平台
#define		STEP_JYLJ			796			//交易配置文件路径
#define		STEP_DRYK			797			//当日盈亏
#define		STEP_CCBZJ			798			//持仓保证金
#define		STEP_THBZJ			799			//提货保证金
#define		STEP_CCBZJ1			800			//仓储保证金
#define		STEP_SSFY			801			//ETF申赎费用
#define		STEP_SSDJFY			802			//ETF认申赎费冻结
#define		STEP_SJXJCE			803			//实际现金差额
#define		STEP_YGXJCE			804			//预估现金差额
#define		STEP_MCL			805			//卖出量
#define		STEP_JYDJ			806			//交易单价
#define		STEP_PCYK			807			//平仓盈亏
#define		STEP_JYDW			808			//交易单位
#define		STEP_DWCB			809			//单位成本
#define		STEP_ZCXE			810			//总仓限额
#define		STEP_QLCXE			811			//权利仓限额
#define		STEP_DRKCXE			812			//单日开仓限额
#define		STEP_JYGT			813			//交易柜台
#define		STEP_DQBZ			814			//到期标志
#define		STEP_ZLCBZJ			815			//中立仓保证金
#define		STEP_XDBS			816			//下单笔数
#define		STEP_ZYJG			817			//止盈价格
#define		STEP_CHBZ			818			//钞汇标志
#define		STEP_RRDC			819			//容忍点差
#define		STEP_GDMS			820			//滚动模式
#define		STEP_TZLX			822			//通知类型
#define		STEP_CHMC			823			//钞汇名称
#define		STEP_BZJYE			824			//保证金余额
#define		STEP_BZJJZ			825			//保证金净值
#define		STEP_ZBJE			828			//追保金额
#define		STEP_QPDMS			829			//强平单模式
#define		STEP_YWTH			830			//原委托号
#define		STEP_SXTS			831			//失效天数
#define		STEP_RZFY			832			//融资费用
#define		STEP_RZLX			833			//融资利息
#define		STEP_KHLX			834			//客户类型
#define		STEP_FXDJ			835			//客户风险等级
#define		STEP_FXDJMC			836			//客户风险等级名称
#define		STEP_BZJMC			837			//保证金名称
#define		STEP_LXDZ			838			//联系地址
#define		STEP_JGDM			839			//机构代码
#define		STEP_KHJLH			840			//客户经理号
#define		STEP_QYZT			841			//签约状态
#define		STEP_PZLX			842			//品种类型
#define		STEP_RZGFYE			843			//融资股份余额
#define		STEP_RZGFKY			844			//融资股份可用
#define		STEP_WTBM			845			//问题编码
#define		STEP_SJLX			846			//试卷类型
#define		STEP_XX1			847			//选项1
#define		STEP_XX2			848			//选项2
#define		STEP_XX3			849			//选项3
#define		STEP_XX4			850			//选项4
#define		STEP_XX5			851			//选项5
#define		STEP_XX6			852			//选项6
#define		STEP_XX7			853			//选项7
#define		STEP_FS1			854			//选项1分值
#define		STEP_FS2			855			//选项2分值
#define		STEP_FS3			856			//选项3分值
#define		STEP_FS4			857			//选项4分值
#define		STEP_FS5			858			//选项5分值
#define		STEP_FS6			859			//选项6分值
#define		STEP_FS7			860			//选项7分值
#define		STEP_CPFS			861			//测评分数
#define		STEP_XXSL			862			//选项数量
#define		STEP_CHRQ			863			//偿还日期
#define		STEP_HYSL			864			//合约数量
#define		STEP_HYJE			865			//合约金额
#define		STEP_RZRQXF			866			//融资融券息费
#define		STEP_WHSL			867			//未还数量
#define		STEP_WHJE			868			//未还金额
#define		STEP_WGFXF			869			//未归还息费
#define		STEP_HYZT			870			//合约状态
#define		STEP_HYLX			871			//合约类型
#define		STEP_TCBH			872			//头寸编号
#define		STEP_HTBH			873			//合约编号
#define		STEP_DQRQ			874			//到期日期
#define		STEP_ZQTS			875			//展期天数
#define		STEP_FZBH			876			//负债编号
#define		STEP_SPRQ			877			//审批日期
#define		STEP_SPPZ			878			//审批批注
#define		STEP_XWLB			879			//席位类别
#define		STEP_PCLX			880			//平仓类型
#define		STEP_CPDM			881			//产品代码
#define		STEP_MRYHDC			882			//买入优惠点差
#define		STEP_MCYHDC			883			//卖出优惠点差
#define		STEP_GYLL1			884			//隔夜利率(第一货币存款)
#define		STEP_GYLL2			885			//隔夜利率(第一货币贷款)
#define		STEP_GYLL3			886			//隔夜利率(第二货币存款)
#define		STEP_GYLL4			887			//隔夜利率(第二货币贷款)
#define		STEP_BZJBL			888			//保证金比例
#define		STEP_GDPLD			889			//挂单偏离度
#define		STEP_HSZBX			890			//黄色追保线
#define		STEP_HSQPX			891			//红色强平线
#define		STEP_MRRRDC			892			//默认容忍点差
#define		STEP_ZDRRDC			893			//最大容忍点差
#define		STEP_GYXC			894			//隔夜息差
#define		STEP_PBJGDM			895			//澎博机构代码
#define		STEP_HXZH			896			//核心帐号
#define		STEP_CWBZ			897			//错误标识
#define		STEP_CCXX			898			//出错消息
#define		STEP_GPJC			899			//股票简称
#define		STEP_GFLB			900			//股份类别
#define		STEP_GDDHBH			901			//股东大会编号
#define		STEP_GDDHMC			902			//股东大会名称
#define		STEP_GDDJR			903			//股东登记日
#define		STEP_ZHJYR			904			//最后交易日
#define		STEP_YABH			905			//议案编号
#define		STEP_YAMC			906			//议案名称
#define		STEP_YALX			907			//议案类型
#define		STEP_YALXMC			908			//议案类型名称
#define		STEP_GSDM			909			//公司代码
#define		STEP_GSJC			910			//公司简称
#define		STEP_TPSL			911			//投票数量
#define		STEP_TPYJ			912			//投票意见
#define		STEP_TPYJMC			913			//投票意见名称
#define		STEP_ZWSJ			914			//指纹数据
#define		STEP_ZYTS			915			//实际占用天数
#define		STEP_QTSZ			916			//其他市值
#define		STEP_DZXX			917			//地址信息
#define		STEP_LJZT			918			//连接状态
#define		STEP_GZBZ			919			//告知标识
#define		STEP_EMAIL			920			//客户Email地址
#define		STEP_YJTZ			921			//是否EMAIL通知
#define		STEP_WPBZ			922			//外盘标志
#define		STEP_CFJG			923			//触发价格
#define		STEP_KHXM			924			//客户姓名
#define		STEP_ZTMC			925			//状态名称
#define		STEP_JYZH			926			//交易账户
#define		STEP_KHRQ			927			//开户日期
#define		STEP_XB			928			//性别
#define		STEP_TXDZ			929			//通讯地址
#define		STEP_YZBM			930			//邮政编码
#define		STEP_ZHQM			931			//账号全名
#define		STEP_STLX			932			//试题类型
#define		STEP_TMNR			933			//题目内容(文本方式)
#define		STEP_YEPH			934			//业务批号
#define		STEP_TZZFL			935			//投资者分类
#define		STEP_TZZDQR			936			//投资者分类到期日
#define		STEP_CPZT			937			//测评状态
#define		STEP_SJLB			938			//试卷类别
#define		STEP_JKRQ			939			//缴款日期
#define		STEP_TZPZ			940			//投资品种
#define		STEP_TZPZMC			941			//投资品种名称
#define		STEP_TZQX			942			//投资期限
#define		STEP_YHLX			943			//用户类型
#define		STEP_YHLXMC			944			//用户类型名称
#define		STEP_TZQXMC			945			//投资期限名称
#define		STEP_YQSY			946			//预期收益
#define		STEP_HBZRJE			947			//货币质入金额
#define		STEP_HBZCJE			948			//货币质出金额
#define		STEP_HBZYYE			949			//货币质押余额
#define		STEP_HBZYJE			950			//可质押货币金额
#define		STEP_BZJ1			951			//特殊产品占用保证金
#define		STEP_DJBZJ1			952			//特殊产品冻结保证金
#define		STEP_SXF1			953			//特殊产品手续费
#define		STEP_DJSXF1			954			//特殊产品冻结手续费
#define		STEP_CCYK1			955			//特殊产品持仓盈亏
#define		STEP_PCYK1			956			//特殊产品平仓盈亏
#define		STEP_TCBZ			957			//退出标志
#define		STEP_WCPBZ			958			//未测评标志(暂废)
#define		STEP_KCPRQ			959			//可测评日期
#define		STEP_KYQLCXE			960			//可用权利仓限额
#define		STEP_DRKYKCXE			961			//可用当日累计买入开仓限额
#define		STEP_KYZCCXE			962			//可用总持仓限额
#define		STEP_QLCCCXE			963			//权利仓持仓限额
#define		STEP_DRMRKCXE			964			//当日累计买入开仓限额
#define		STEP_ZCCXE			965			//总持仓限额
#define		STEP_SQSSJ			966			//上期所时间
#define		STEP_ZSSSJ			967			//郑商所时间
#define		STEP_DSSSJ			968			//大商所时间
#define		STEP_ZJSSJ			969			//中金所时间
#define		STEP_NYJYSJ			970			//能源交易所时间
#define		STEP_GZNR			971			//风险测评告知内容
#define		STEP_XYNR			972			//协议内容
#define		STEP_XYLB			973			//风险协议类型
#define		STEP_SFQS			974			//是否已签署
#define		STEP_XYGS			975			//协议格式
#define		STEP_XYQSBZ			976			//协议签署标志
#define		STEP_WTHLB			977			//委托列表
#define		STEP_RQFZ			978			//融券负债
#define		STEP_CXBZ			979			//查询标志
#define		STEP_DLZD			980			//登录站点
#define		STEP_ZDCLX			981			//自对冲类型
#define		STEP_ZDCMC			982			//自对冲名称
#define		STEP_JGBZJ			983			//交割保证金
#define		STEP_JYSJGBZJ			984			//交易所交割保证金
#define		STEP_CCLX			985			//持仓类型
#define		STEP_ZQRQ			986			//中签日期
#define		STEP_ZQJE			987			//中签金额
#define		STEP_JKJE			988			//缴款金额
#define		STEP_FXFSMC			989			//发行方式名称
#define		STEP_HYZTMC			990			//合约状态名称
#define		STEP_HYLXMC			991			//合约类型名称
#define		STEP_QQBZ			992			//请求标志
#define		STEP_RZLJ			993			//日志路径
#define		STEP_WTLX			994			//委托类型
#define		STEP_WTLXMC			995			//委托类型名称
#define		STEP_JYJSF			996			//交易经手费
#define		STEP_JYJSF1			997			//交易结算费
#define		STEP_XQJSF			998			//行权结算费
#define		STEP_ZDJC			999			//自动净仓标志
#define		STEP_IMSI			1000			//手机的IMSI
#define		STEP_BD_HYDM			1001			//本地合约代码
#define		STEP_BD_FDYK			1002			//本地浮动盈亏
#define		STEP_BD_CCSZ			1003			//本地总持仓市值
#define		STEP_BD_HYSZ			1004			//本地合约市值
#define		STEP_BD_JYSFXD			1005			//对应交易所风险度的倒数
#define		STEP_BD_SRFXD			1006			//对应上日风险度的倒数
#define		STEP_BD_JZCZT			1007			//对应本地使用的今昨仓状态
#define		STEP_SCJSJ			2000			//上次结算价
#define		STEP_ZSJ			2001			//昨收价
#define		STEP_ZCCL			2002			//昨持仓量
#define		STEP_JKJ			2003			//今开价
#define		STEP_ZGJ			2004			//最高价
#define		STEP_ZDJ			2005			//最低价
#define		STEP_SPJ			2006			//收盘价
#define		STEP_BY			2007			//备用
#define		STEP_CCL			2008			//持仓量
#define		STEP_JSJ			2009			//结算价
#define		STEP_ZTJ			2010			//涨停价
#define		STEP_DTJ			2011			//跌停价
#define		STEP_ZXSD			2012			//昨虚实度
#define		STEP_JXSD			2013			//今虚实度
#define		STEP_ZHGXSJ			2014			//最后更新时间
#define		STEP_BUY1			2015			//买价一
#define		STEP_BUY_VOLUME1			2016			//买量一
#define		STEP_BUY2			2017			//买价二
#define		STEP_BUY_VOLUME2			2018			//买量二
#define		STEP_BUY3			2019			//买价三
#define		STEP_BUY_VOLUME3			2020			//买量三
#define		STEP_BUY4			2021			//买价四
#define		STEP_BUY_VOLUME4			2022			//买量四
#define		STEP_BUY5			2023			//买价五
#define		STEP_BUY_VOLUME5			2024			//买量五
#define		STEP_SELL1			2025			//卖价一
#define		STEP_SELL_VOLUME1			2026			//卖量一
#define		STEP_SELL2			2027			//卖价二
#define		STEP_SELL_VOLUME2			2028			//卖量二
#define		STEP_SELL3			2029			//卖价三
#define		STEP_SELL_VOLUME3			2030			//卖量三
#define		STEP_SELL4			2031			//卖价四
#define		STEP_SELL_VOLUME4			2032			//卖量四
#define		STEP_SELL5			2033			//卖价五
#define		STEP_SELL_VOLUME5			2034			//卖量五
#define		STEP_JJ			2035			//均价
#define		STEP_YWRQ			2036			//业务日期
#define		STEP_BUY6			2037			//买价六
#define		STEP_BUY_VOLUME6			2038			//买量六
#define		STEP_BUY7			2039			//买价七
#define		STEP_BUY_VOLUME7			2040			//买量七
#define		STEP_BUY8			2041			//买价八
#define		STEP_BUY_VOLUME8			2042			//买量八
#define		STEP_BUY9			2043			//买价九
#define		STEP_BUY_VOLUME9			2044			//买量九
#define		STEP_BUY10			2045			//买价十
#define		STEP_BUY_VOLUME10			2046			//买量十
#define		STEP_SELL6			2047			//卖价六
#define		STEP_SELL_VOLUME6			2048			//卖量六
#define		STEP_SELL7			2049			//卖价七
#define		STEP_SELL_VOLUME7			2050			//卖量七
#define		STEP_SELL8			2051			//卖价八
#define		STEP_SELL_VOLUME8			2052			//卖量八
#define		STEP_SELL9			2053			//卖价九
#define		STEP_SELL_VOLUME9			2054			//卖量九
#define		STEP_SELL10			2055			//卖价十
#define		STEP_SELL_VOLUME10			2056			//卖量十
#define		STEP_JGBL			2057			//交割买量
#define		STEP_JGSL			2058			//交割卖量
#define		STEP_ZLCBL			2059			//中立仓买量
#define		STEP_ZLCSL			2060			//中立仓卖量
#define		STEP_LOGID			2063			//日志ID
#define		STEP_MYKL			2066			//客户端密钥
#define		STEP_LOCAL_INFO			2067			//穿透式监管终端硬件信息
#define		STEP_POBO5_RECONNECT			3001			//博易5CTP重连使用
#define		STEP_RZSJ			5001			//日志时间
#define		STEP_QQYDBZ			5002			//请求应答标志
#define		STEP_FUNCNAME			5003			//功能名称
#define		STEP_YHXH			5004			//用户序号
#define		STEP_IP			5005			//终端的公网IP
#define		STEP_PTMC			5006			//终端的平台名称
#define		STEP_CPMC			5007			//产品名称
#define		STEP_ZDBM			5008			//站点编码
#define		STEP_STEP_L_T_REQNO			5900			//中间件用于临时存储上层的请求编号
#define		STEP_XTPJDJ			7001			//系统风险级别
#define		STEP_XTDJMC			7002			//系统风险级别名称
#define		STEP_XL			7003			//学历
#define		STEP_ZY			7004			//职业
#define		STEP_XLMC			7005			//学历名称
#define		STEP_ZYMC			7006			//职业名称
#define		STEP_GTHHBZ			7007			//柜台会话标识
#define		STEP_BDBDXH			7008			//本地报单序号
#define		STEP_WTDJZJ			7009			//委托冻结资金-
#define		STEP_CZXTBB			7010			//操作系统版本
#define		STEP_GTDWC			7011			//柜台定位串
#define		STEP_CDBZ			7012			//撤销标志
#define		STEP_CJLX			7013			//成交类型
#define		STEP_QQHS			7014			//请求行数
#define		STEP_CJBZ			7015			//成交标志
#define		STEP_CJBS			7016			//成交笔数
#define		STEP_SQWJ			7017			//授权文件
#define		STEP_PZWJ			7021			//配置文件
#define		STEP_RSAKEY			7029			//RSA公钥
#define		STEP_JYSDBZ			7030			//交易时段标志
#define		STEP_RZMWJ			7031			//穿透式授权码文件
#define		STEP_YCBS			7040			//穿透式监管异常标志
#define		STEP_XXWZD			7041			//穿透式监管信息完整度
#define		STEP_CTSMYBB			7042			//穿透式密钥版本
#define		STEP_AQMY			7052			//安全密钥
#define		STEP_SQM			7053			//穿透式密钥版本
#define		STEP_CTSBB			7054			//穿透式版本
#define		STEP_APPID			7058			//终端APPID
#define		STEP_SJJGS			7063			//时间间隔
#define		STEP_JYZZT			7130			//交易子状态

#endif